/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Bookings: () => import('#controllers/bookings_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Packages: () => import('#controllers/packages_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Session: () => import('#controllers/session_controller'),
}
