/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookingSchema extends BaseModel {
  static $columns = ['id', 'userId', 'name', 'phone', 'date', 'time', 'servicesJson', 'status', 'overbooked', 'createdAt', 'updatedAt'] as const
  $columns = BookingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare name: string
  @column()
  declare phone: string
  @column.date()
  declare date: DateTime
  @column()
  declare time: string
  @column()
  declare servicesJson: any
  @column()
  declare status: string
  @column()
  declare overbooked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PackageSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'price', 'createdAt', 'updatedAt', 'duration'] as const
  $columns = PackageSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare description: string
  @column()
  declare price: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare duration: number | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'hash', 'createdAt', 'updatedAt', 'expiresAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare hash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'phone', 'email', 'password', 'role', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare phone: string
  @column()
  declare email: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
